# Generated by Django 5.1.3 on 2024-11-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_flat_delete_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flat',
        ),
    ]
