# Generated by Django 5.1.3 on 2024-11-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='created_by_username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
