# Generated by Django 5.1.3 on 2024-11-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_flatmate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatmate',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='flatmate',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
