# Generated by Django 5.1.3 on 2024-11-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_first_name_flatmate_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='numOfFlatmates',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
