# Generated by Django 5.1.3 on 2024-11-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_flat_numofflatmates'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
