# Generated by Django 5.1.3 on 2024-11-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_flat_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='numOfFlatmates',
            field=models.IntegerField(default=1),
        ),
    ]
