# Generated by Django 5.1.3 on 2024-11-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatmate',
            name='isadmin',
            field=models.BooleanField(default=False),
        ),
    ]
