# Generated by Django 5.1.3 on 2024-11-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_account_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatmate',
            name='accnum',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
