# Generated by Django 5.1.3 on 2024-11-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_loan_user_loan_recipient_loan_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='paid',
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
