# Generated by Django 5.1.3 on 2024-12-01 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_loan_paid_loan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.flat')),
            ],
            options={
                'ordering': ['due_date', 'due_time'],
            },
        ),
    ]
