# Generated by Django 5.1.3 on 2024-12-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_sharedexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedexpense',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
