# Generated by Django 5.1.3 on 2024-12-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_sharedexpense_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='shared_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
