# Generated by Django 5.1.3 on 2024-12-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_flat_shared_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatmate',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
