# Generated by Django 5.1.3 on 2024-12-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_partyfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyfund',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partyfund',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
