# Generated by Django 5.1.3 on 2024-12-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_partyfund_due_date_partyfund_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyfund',
            name='due_date',
        ),
    ]
