# Generated by Django 5.1.3 on 2024-12-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_partyfund_per_person_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyfund',
            name='per_person_cost',
        ),
    ]
