# Generated by Django 5.1.3 on 2024-12-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_partyfund_per_person_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyfund',
            name='per_person_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
