# Generated by Django 5.1.3 on 2024-12-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_partyfund_per_person_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyfund',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
