# Generated by Django 5.1.3 on 2024-12-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_partyfund_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedexpense',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
